name: ForgeItems
#名称
main: com.github.sunligh91.forge.main.ForgeItem
#包名+主类名
version: 1.0.0
#版本
commands:
  dj:
    description: 鉴定系统
    usage: 错误的指令，请输入dj查看指令列表
    permission: dj.all
    permission-message: 你没有这个权限！
  djr:
    description: 重新读取配置文件
    usage: 错误的指令，请输入djr查看指令列表
    permission: djr.all
    permission-message: 你没有这个权限！
permissions:
  dj.all:
    default: true
  djr.all:
    default: op